name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get -y install portaudio19-dev libportmidi-dev
      - name: Install latest nim
        run: |
            curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
            echo "/home/runner/.nimble/bin" >> $GITHUB_PATH
      - name: Install nimgl
        run: nimble install -y nimgl
      - name: Build nara
        run: nim cpp --threads:on -d:release nara.nim
